[workspace]
members = [
    "contracts/betting-account",
    "contracts/higher-than-seven-note",
    "integration"
]
resolver = "2"
edition = "2021"

[workspace.dependencies]
miden = { version = "0.7" }
